=== CristianGM1994/CarpetaPracticaEntorno/xschema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="instrumentos">
    <xs:complexType>
       <xs:sequence>
        <xs:element name="clasitipos">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="tipo">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nombretipo" type="xs:string" />
                    <xs:element name="definiciontipo" type="xs:string" />
                    <xs:element maxOccurs="unbounded" name="Formaomodo">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="idmodo" type="xs:string" use="required" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="idtipo" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="unbounded" name="instrumento">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombreinstru" type="xs:string" />
              <xs:element name="imageninstru" type="xs:string" />
              <xs:element name="historia" type="xs:string" />
              <xs:element name="otroinstrumentosrel" type="xs:string" />
              <xs:element name="interpretes">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="interprete">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="nameinter" type="xs:string" />
                          <xs:element name="surname" type="xs:string" />
                          <xs:element name="paiscountry" type="xs:string" />
                          <xs:element name="imageninterprete" type="xs:string" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="idmodo" type="xs:string" use="required" />
            <xs:attribute name="idtipo" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== CristianGM1994/CarpetaPracticaEntorno/PracticaXMLEntregable.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--instrumentos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xschema.xsd">-->

<!DOCTYPE instrumentos [
	<!ELEMENT instrumentos (clasitipos+,instrumento+)>
	<!ELEMENT clasitipos (tipo+)>
	<!ELEMENT tipo (nombretipo,definiciontipo,Formaomodo+)>
	<!ATTLIST tipo idtipo ID #REQUIRED>
	<!ELEMENT nombretipo (#PCDATA)>
	<!ELEMENT definiciontipo (#PCDATA)>
	<!ELEMENT Formaomodo (#PCDATA)>
	<!ATTLIST Formaomodo idmodo ID #REQUIRED>
	<!ELEMENT instrumento (nombreinstru+,imageninstru+,historia+,otroinstrumentosrel+,interpretes+)>
	<!ATTLIST instrumento idmodo IDREF #REQUIRED>
	<!ATTLIST instrumento idtipo IDREF #REQUIRED>
	<!ELEMENT nombreinstru (#PCDATA)>
	<!ELEMENT imageninstru (#PCDATA)>
	<!ELEMENT historia (#PCDATA)>
	<!ELEMENT otroinstrumentosrel (#PCDATA)>
	<!ELEMENT interpretes (interprete+)>
	<!ELEMENT interprete (nameinter+,surname+,paiscountry+,imageninterprete+)>
	<!ELEMENT nameinter (#PCDATA)>
	<!ELEMENT surname (#PCDATA)>
	<!ELEMENT paiscountry (#PCDATA)>
	<!ELEMENT imageninterprete (#PCDATA)>
	]>	
	
	<instrumentos>
	<clasitipos>	
        <tipo idtipo="cordofo">
			<nombretipo>Cordofono</nombretipo>
			<definiciontipo>Sonido se produce al vibrar una CUERDA tensa</definiciontipo>
			<Formaomodo idmodo="frota1">Frotada</Formaomodo>
            <Formaomodo idmodo="pulsadaopelliz">Pulsada O Pellizcada</Formaomodo>
            <Formaomodo idmodo="percupiano">Percutida Con Piano</Formaomodo>
		</tipo>
        
        <tipo idtipo="membra">
			<nombretipo>Membranofonos</nombretipo>
			<definiciontipo>Sonido se produce al vibrar una MEMBRANA</definiciontipo>
			<Formaomodo idmodo="percutir">Percutidos</Formaomodo>
			<Formaomodo idmodo="frota2">Frotados</Formaomodo>
            <Formaomodo idmodo="sopla2">Soplados</Formaomodo>
		</tipo>
	    
        
		<tipo idtipo="aerofo">
			<nombretipo>Aerófonos</nombretipo>
			<definiciontipo>Sonido se produce al vibrar una COLUMNA de aire</definiciontipo>
			<Formaomodo idmodo="boquillaoemp">Boquilla o Empuñadura</Formaomodo>
			<Formaomodo idmodo="bis">Bisel</Formaomodo>
		    <Formaomodo idmodo="lenguetasimp">Lengueta Simple</Formaomodo>
			<Formaomodo idmodo="lenguetadob">Lengueta Doble</Formaomodo>
			<Formaomodo idmodo="lenguetalibr">Lengueta Libre</Formaomodo>
			<Formaomodo idmodo="mix">Mixta</Formaomodo>
		</tipo>
        
        <tipo idtipo="electricos">
			<nombretipo>Electrofonos</nombretipo>
			<definiciontipo>Sonido se produce por medios ELECTRICOS</definiciontipo>
			<Formaomodo idmodo="tradicion">Instrumentos Tradicionales</Formaomodo>
            <Formaomodo idmodo="NewConstruccion">Nueva Construccion</Formaomodo>
		</tipo>
	

		<tipo idtipo="idiofo">
			<nombretipo>Idiofonos</nombretipo>
			<definiciontipo>Sonido se produce al vibrar el PROPIO CUERPO del instrumento</definiciontipo>
			<Formaomodo idmodo="entrechoq">Entrechoque</Formaomodo>
			<Formaomodo idmodo="golpeopercu">Golpeado o Percutido</Formaomodo>
            <Formaomodo idmodo="sacu">Sacudidas</Formaomodo>
            <Formaomodo idmodo="raspas">Raspados</Formaomodo>
            <Formaomodo idmodo="punte">Punteados</Formaomodo>
            <Formaomodo idmodo="frota">Frotados</Formaomodo>
            <Formaomodo idmodo="sopla">Soplados</Formaomodo>
        </tipo>
    </clasitipos>
     
      <!--1-->
	<instrumento idmodo="boquillaoemp" idtipo="aerofo">
		<nombreinstru>Tuba</nombreinstru>
		<imageninstru>https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Two_F_tubas.jpg/220px-Two_F_tubas.jpg</imageninstru>
		<historia>La tuba es el mayor de los instrumentos de viento-metal y sus antecesores son el serpentón y el oficleido. Es uno de los instrumentos más recientemente añadidos a la orquesta sinfónica moderna</historia>
		<otroinstrumentosrel>Bombardino</otroinstrumentosrel>
		<interpretes>
			<interprete>
				<nameinter>Gene</nameinter>
				<surname>Pokorny</surname>
				<paiscountry>America</paiscountry>
				<imageninterprete>https://welltempered.files.wordpress.com/2013/07/gene-pokorny-tuba.jpg</imageninterprete>
			</interprete>
			<interprete>
				<nameinter>Walter </nameinter>
				<surname>Hilgers </surname>
				<paiscountry>Stolberg, Alemania</paiscountry>
                <imageninterprete>http://3.bp.blogspot.com/-DiyWVGBdeNI/VlDUkbj-cRI/AAAAAAAAA20/emGljdxprOs/s1600/WALTER_HILGER_PLAYS_ON_MELTON_TUBAS.jpg </imageninterprete>
			</interprete>
		</interpretes>
	</instrumento>
    
     <!--2-->
    <instrumento idmodo="boquillaoemp" idtipo="aerofo">
		<nombreinstru>Trompa</nombreinstru>
		<imageninstru>https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/French_horn_front.png/200px-French_horn_front.png</imageninstru>
		<historia>La trompa o corno francés es un instrumento de viento-metal que tiene un carácter muy versátil y abarca una tesitura muy amplia con pocos pistones</historia>
		<otroinstrumentosrel>Trompa Natural</otroinstrumentosrel>
		<interpretes>
			<interprete>
				<nameinter>Miguel</nameinter>
				<surname>Falomir Sabater</surname>
				<paiscountry>España</paiscountry>
				<imageninterprete>http://4.bp.blogspot.com/_LUJLp0pR7TA/TKcDCjrHtvI/AAAAAAAAAAg/rXJVgNKWE8w/s320/Falomir.JPG</imageninterprete>
			</interprete>
			<interprete>
				<nameinter>Salvador </nameinter>
				<surname>Norte </surname>
				<paiscountry>España</paiscountry>
                <imageninterprete>http://3.bp.blogspot.com/_LUJLp0pR7TA/TKcuUE6srEI/AAAAAAAAAAs/6xj_OOdub1Y/s1600/Salvador+norte.JPG</imageninterprete>
			</interprete>
		</interpretes>
	</instrumento>
     
     <!--3-->
    <instrumento idmodo="NewConstruccion" idtipo="electricos">
		<nombreinstru>Sintetizador</nombreinstru>
		<imageninstru>https://upload.wikimedia.org/wikipedia/commons/3/3e/R.A.Moog_minimoog_2.jpg</imageninstru>
		<historia>Un sintetizador es un instrumento musical electrónico que genera señales eléctricas convertidas a sonidos a través de altavoces o auriculares.</historia>
		<otroinstrumentosrel>Organo</otroinstrumentosrel>
		<interpretes>
			<interprete>
				<nameinter>Rick</nameinter>
				<surname>Wakeman</surname>
				<paiscountry>Reino Unido</paiscountry>
				<imageninterprete>https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Rickwakemanmoog.jpg/250px-Rickwakemanmoog.jpg</imageninterprete>
			</interprete>
			<interprete>
				<nameinter>Skinny</nameinter>
				<surname>Puppy</surname>
				<paiscountry>Vancouver, Canada</paiscountry>
                <imageninterprete>https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Skinny_Puppy_live_at_London_Astoria%2C_August_10_2005_4.jpg/250px-Skinny_Puppy_live_at_London_Astoria%2C_August_10_2005_4.jpg</imageninterprete>
			</interprete>
		</interpretes>
	</instrumento>
    
     <!--4-->
    <instrumento idmodo="boquillaoemp" idtipo="aerofo">
		<nombreinstru>Trombon</nombreinstru>
		<imageninstru>https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Posaune.gif/200px-Posaune.gif</imageninstru>
		<historia>El trombón es un instrumento de viento metal. Su sonido se produce gracias a la vibración de los labios del intérprete en la parte denominada boquilla a partir de la columna del aire (flujo del aire)</historia>
		<otroinstrumentosrel>Tuba</otroinstrumentosrel>
		<interpretes>
			<interprete>
				<nameinter>Christian</nameinter>
				<surname>Lindberg</surname>
				<paiscountry>Suecia</paiscountry>
				<imageninterprete>http://www.epdlp.com/fotos/lindberg.jpg</imageninterprete>
			</interprete>
			<interprete>
				<nameinter>Willie</nameinter>
				<surname>Colon</surname>
				<paiscountry>Nueva York</paiscountry>
                <imageninterprete>http://www.fundacionjoseguillermocarrillo.com/sitio/fotos/willie.jpg</imageninterprete>
			</interprete>
		</interpretes>
	</instrumento>
    
     <!--5-->
    <instrumento idmodo="boquillaoemp" idtipo="aerofo">
		<nombreinstru>Helicon</nombreinstru>
		<imageninstru>https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Posaune.gif/200px-Posaune.gif</imageninstru>
		<historia>El helicón es un instrumento de viento-metal. Es el predecesor del sousafón y ambos instrumentos tienen formas circulares y son típicamente portados sobre el hombro.</historia>
		<otroinstrumentosrel>Trompa</otroinstrumentosrel>
		<interpretes>
			<interprete>
				<nameinter>Guardia</nameinter>
				<surname>Republicana</surname>
				<paiscountry>Francia</paiscountry>
				<imageninterprete>http://i2.esmas.com/2013/07/29/547567/1298248251757ebe5b274e738c0f08902ae68004-619x348.jpg</imageninterprete>
			</interprete>
			<interprete>
				<nameinter>Guardia</nameinter>
				<surname>Republicana</surname>
				<paiscountry>Nueva York</paiscountry>
                <imageninterprete>http://i2.esmas.com/2013/07/29/547567/1298248251757ebe5b274e738c0f08902ae68004-619x348.jpg</imageninterprete>
			</interprete>
		</interpretes>
	</instrumento>
    
     <!--6-->
    <instrumento idmodo="NewConstruccion" idtipo="electricos">
		<nombreinstru>Theremín</nombreinstru>
		<imageninstru>https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Etherwave_Theremin_Kit.jpg/800px-Etherwave_Theremin_Kit.jpg</imageninstru>
		<historia>El theremín es un instrumento musical inventado en 1919 por el ruso Lev Termen (1896-1993). Fue uno de los primeros instrumentos musicales electrónicos y, además de su sonido, lo más curioso es que el ejecutante no tiene ningún contacto físico con él.</historia>
		<otroinstrumentosrel>Trompa alto</otroinstrumentosrel>
		<interpretes>
			<interprete>
				<nameinter>Led</nameinter>
				<surname>Zeppelin</surname>
				<paiscountry>Londres, Reino Unido</paiscountry>
				<imageninterprete>https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Led_Zeppelin_logo.svg/250px-Led_Zeppelin_logo.svg.png</imageninterprete>
			</interprete>
			<interprete>
				<nameinter>Kasper</nameinter>
				<surname>Eistrup</surname>
				<paiscountry>Dinamarca</paiscountry>
